@host=https://localhost:7270

POST {{host}}/auth/register
Content-Type: application/json

{
  "firstName" : "sajjad",
  "lastName" : "golcohin",
  "email": "sajjad.gol@gmail.com",
  "password" : "123456"
}